import { getAuth } from 'firebase/auth'
import Head from 'next/head'
import Image from 'next/image'
import { useAuth } from 'lib/auth'
import styles from 'styles/Home.module.css'
import { Button, ButtonGroup, Code, Heading, Text } from '@chakra-ui/react'

export default function Home () {
  const getAuth = useAuth();

  return <div>
      <Head>

      <title>Sibol</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
        
      </Head>

      <main>
        <Heading>
          Sibol Admin Login
        </Heading>

        <Text>
          Current user: <Code>{getAuth.user ? getAuth.user.name : 'None'}</Code>
          <br>
          </br>
          Email: <Code>{getAuth.user ? getAuth.user.email : 'None'}</Code>
        </Text>
        {getAuth.user ? (
          <Button onClick={(e) => getAuth.signout()}>Sign Out</Button>
        ) : (
          <Button onClick={(e) => getAuth.signinWithGithub()}>Login</Button>
        )}

      </main>
    </div>
}
